import { TAppSchema } from './schema';

export const mockedSettings: TAppSchema = {
    camera_protocol: 'http',
    camera_ip: '10.5.7.2.',
    camera_port: 80,
    camera_user: 'root',
    camera_pass: '',
    unit: 'f',
    service_id: 1,
    field_name: 'field1',
    acs_protocol: 'http',
    acs_ip: '',
    acs_port: 55756,
    acs_user: '',
    acs_pass: '',
    acs_source_key: '',
    acs_condition_delay: 10800,
    acs_condition_operator: 0,
    acs_condition_value: 10,
    acs_repeat_after: 30,
    event_camera_protocol: 'http',
    event_camera_ip: '1.1.1.1.',
    event_camera_port: 80,
    event_camera_user: 'root',
    event_camera_pass: '',
    event_condition_delay: 120,
    event_condition_operator: 3,
    event_condition_value: 10,

    event_camera_list: [2, 3],
    event_active: true,
    event_repeat_after: 30,
    camera_list: [0, 1],
    acs_active: true,
};
