import { TAppSchema } from './schema';

export const mockedSettings: TAppSchema = {
  camera_protocol: 'http',
  camera_ip: '10.5.7.2.',
  camera_port: 80,
  camera_user: 'root',
  camera_pass: '',
  unit: 'f',
  service_id: 1,
  field_name: 'field1',
  acs_protocol: 'http',
  acs_ip: '',
  acs_port: 55756,
  acs_user: '',
  acs_pass: '',
  acs_source_key: '',
  acs_condition_delay: 10800,
  acs_condition_operator: 0,
  acs_condition_value: 10,
  acs_repeat_after: 30,
  event_camera_protocol: 'http',
  event_camera_ip: '1.1.1.1.',
  event_camera_port: 80,
  event_camera_user: 'root',
  event_camera_pass: 'pass',
  event_condition_delay: 120,
  event_condition_operator: 3,
  event_condition_value: 10,

  event_view_areas: [
    { value: 0, label: 'View Area 1' },
    { value: 1, label: 'View Area 2' },
    { value: 2, label: 'View Area 3' },
    { value: 3, label: 'View Area 4' },
  ],
  event_active: true,
  event_repeat_after: 30,
  view_areas: [
    { value: 0, label: 'View Area 1' },
    { value: 1, label: 'View Area 2' },
  ],
  acs_active: true,
};
