import { TServerData } from './schema';

export const mockedSettings: TServerData = {
    barcode_validation_rule: '',
    conn_hub: {
        protocol: 'http',
        ip: '',
        port: 80,
        user: 'root',
        pass: '',
    },
    camera: {
        protocol: 'http',
        ip: '',
        port: 80,
        user: 'root',
        pass: '',
        serial_number: '',
    },
    output_camera: {
        protocol: 'http',
        ip: '',
        port: 80,
        user: 'root',
        pass: '',
    },
    image_upload: {
        camera_list: [0],
        resolution: '1920x1080',
    },
    video_upload: {
        prebuffer_sec: 10,
        postbuffer_sec: 10,
        timeout_enabled: true,
        timeout_sec: 300,
        closing_barcode_enabled: false,
        closing_barcode: '',
        starting_barcode_enabled: false,
        starting_barcode: '',
        camera_list: [0],
    },
    widget: {
        scale: 100,
        coord_system: 'top_left',
        pos_x: 0,
        pos_y: 0,
        stream_resolution: '1920x1080',
        camera_list: [0],
        visibility_time_sec: 10,
    },
    axis_events: {
        conn_hub: false,
        camera: false,
    },
    acs: {
        protocol: 'http',
        ip: '',
        port: 29204,
        user: 'root',
        pass: '',
        enabled: false,
        source_key: '',
    },
    genetec: {
        enabled: false,
        protocol: 'http',
        ip: '',
        port: 4590,
        user: '',
        pass: '',
        base_uri: 'WebSdk',
        app_id: '',
        camera_list: [],
    },
    milestone: {
        enabled: false,
        transaction_source: 'Videocheckpoint',
        port: 8081,
    },
    google_drive: {
        email: '',
        enabled: false,
        type: 'image',
        private_key: '',
        folder_id: '',
    },
    ftp_server: {
        type: 'image',
        protocol: 'ftp',
        ip: '',
        port: 21,
        user: 'root',
        pass: '',
        enabled: false, // This may change to z.union([z.boolean(), z.literal('implicit')])
        upload_path: '',
    },
    share_point: {
        url: '',
        enabled: false,
        output_dir: '',
        client_secret: '',
        client_id: '',
        tenant_id: '',
        connection_timeout_s: 5,
        upload_timeout_s: 30,
        number_of_retries: 3,
    },
    led: {
        enabled: false,
        led_green_port: 2,
        led_red_port: 3,
    },
};
